#!/bin/bash
# PROTOTYPE - wayfinder ticket 06. THROWAWAY.
#
# Seeds a self-contained aardvark system that the Alfred probe writes into, so
# `add_id` really creates folders and index rows without touching your live
# "My Life" system. Also writes workflow/scripts/env.sh - the absolute
# interpreter, binary, settings and root paths the Alfred scripts source,
# because Alfred's PATH cannot see a conda environment.
#
# Safe to re-run: it wipes and rebuilds the throwaway system every time.
set -euo pipefail
cd "$(dirname "$0")"

THROWAWAY_DIR="${AARDVARK_TICKET06_DIR:-$HOME/.aardvark-ticket06-throwaway}"
SYSTEM_NAME="Ticket06"
SETTINGS="$THROWAWAY_DIR/settings.yaml"
ROOT="$THROWAWAY_DIR/$SYSTEM_NAME"

AARDVARK_BIN="$(command -v aardvark || true)"
if [ -z "$AARDVARK_BIN" ]; then
	echo "error: 'aardvark' is not on PATH. Activate the env first (conda activate aardvark-jd)." >&2
	exit 1
fi
# THE CONSOLE SCRIPT'S SHEBANG IS THE ENV PYTHON - THE ONE THAT CAN 'import aardvark_jd'.
AARDVARK_PY="$(head -1 "$AARDVARK_BIN" | sed 's/^#!//')"
if [ ! -x "$AARDVARK_PY" ]; then
	echo "error: could not derive the interpreter from $AARDVARK_BIN (got '$AARDVARK_PY')." >&2
	exit 1
fi

echo "wiping $THROWAWAY_DIR"
rm -rf "$THROWAWAY_DIR"
mkdir -p "$THROWAWAY_DIR"

printf 'version: 1\nsystem:\n  name: null\n  root_path: null\n' > "$SETTINGS"

"$AARDVARK_BIN" init "$SYSTEM_NAME" "$THROWAWAY_DIR" -s "$SETTINGS"

# A SPREAD OF CATEGORIES ACROSS ALL THREE DOMAINS SO STEP 1'S PICKER LIST IS
# LONG ENOUGH TO FEEL REAL - NAMES CHOSEN TO COLLIDE ON PREFIXES ("Car...",
# "Health...") AND TO CONTAIN THE CANDIDATE SEPARATORS.
seed() { "$AARDVARK_BIN" "$@" -s "$SETTINGS" >/dev/null; }

seed add_area A "Health" "body and mind"
seed add_category A10 "Doctors" "GPs and specialists"
seed add_category A10 "Dentists" "check-ups and work"
seed add_category A10 "Fitness" "training and classes"

seed add_area A "Home" "house and contents"
seed add_category A20 "Vehicles" "the car and the bikes"
seed add_category A20 "Insurance - buildings and contents" "policies and claims"
seed add_category A20 "Utilities" "gas, water, electricity, broadband"

seed add_area R "Reference" "things worth keeping"
seed add_category R10 "Recipes" "the ones that actually worked"
seed add_category R10 "Manuals" "appliances and gadgets"

seed add_area P "Projects" "active work"
seed add_category P10 "aardvark-jd :: the CLI" "this project"
seed add_category P10 "House renovation" "kitchen and loft"

mkdir -p workflow/scripts
cat > workflow/scripts/env.sh <<EOF
# GENERATED BY setup.sh - THROWAWAY. Sourced by the Alfred probe scripts.
export AARDVARK_BIN="$AARDVARK_BIN"
export AARDVARK_PY="$AARDVARK_PY"
export AARDVARK_SETTINGS="$SETTINGS"
export AARDVARK_ROOT="$ROOT"
EOF

echo
echo "throwaway system ready:"
echo "  root     $ROOT"
echo "  settings $SETTINGS"
echo "  binary   $AARDVARK_BIN"
echo "  python   $AARDVARK_PY"
echo
echo "categories seeded:"
"$AARDVARK_BIN" fd -s "$SETTINGS" | sed 's/^/  /'
echo
echo "next: ./regen.sh  then import AardvarkArgEntryProbe.alfredworkflow into Alfred."
